### ISSUE TITLE
New Term Request: curriculum

### ISSUE THREAD

**Issue by hectorguzor** [hectorguzor/provisional_OntoEd#12]
create textual definitions and annotations for "curriculum"

**Comment by hectorguzor** [comment]
Discussed on 2024-07-18: Tim will update the annotations for "curriculum" on the `terminology.tsv` and he will create a class for curriculum on `oed.owl`.

**Comment by BrenDragon** [comment]
Curriculum = A course, especially a fixed course of study at a college , university, or school.

**Comment by Tsimmons1234** [comment]
A curriculum is a generically dependent continuant that imparts upon students knowledge of some subject domain.

**Comment by hectorguzor** [comment]
Discussed on 2024-08-15: change label term to "course curriculum". This class would need a few imports from IAO such as [document](http://purl.obolibrary.org/obo/IAO_0000310) and maybe others. Definition should reflect what did document is meant to convey about a particular course (e.g who could teach it, pre-reques etc).

**Comment by hectorguzor** [comment]
@Tsimmons1234 import [document](http://purl.obolibrary.org/obo/IAO_0000310) and create "course curriculum" under [document](http://purl.obolibrary.org/obo/IAO_0000310). as stated above, make sure the textual definition reflects how it fits in the hierarchy by something like "A document that blah blah blah".

**Comment by Tsimmons1234** [comment]
A generically dependent continuant constituted by a collection of information content entities, each entity being about the same subject matter with some entities having a cumulative relationship with others, which imparts upon students proficient knowledge of that subject matter and is determinative of successful completion of a course in that subject matter.
